# dein.toml

# colorscheme
[[plugins]]
repo = 'tomasr/molokai'

### Utils

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# merged = 0

# [[plugins]]
# repo = 'Shougo/deoplete-nextword'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
merged = 0
on_ft = 'nim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'wincent/ferret'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'mhinz/vim-signify'

# [[plugins]]
# repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

### Language support
[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

# Deoplete sources
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'
