# https://github.com/helix-editor/helix/blob/master/runtime/themes/monokai.toml
inherits = "monokai"

"ui.background" = { fg = "text" }
"ui.cursor.match" = { fg = "text", bg = "light-blue" }

"constructor" = { fg = "func_declaration" }
"function" = { fg = "func" }
"function.builtin" = { fg = "func" }

"tag" = { fg = "keyword" }

[palette]
type = "#F8F8F2"
func = "#A6E22E"
func_declaration = "#FFC66D"
