theme = "monokai-custom"

[editor]
color-modes = true
auto-pairs = false

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
L = "goto_line_end"
H = "goto_line_start"
"C-7" = "toggle_comments"
